[package]
name = "wasm-pdf"
version = "0.1.3"
authors = ["Jussi Niinikoski <jussi.niinikoski@perjantai.fi>"]
description = "Generate PDF files with JavaScript and WebAssembly."
keywords = ["wasm", "pdf"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/jussiniinikoski/wasm-pdf/"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = { version = "0.2.48", features = ["serde-serialize"]  }
console_error_panic_hook = "0.1.6"
js-sys = "0.3.25"
serde = { version = "1.0.94", features = ["derive"] }
serde_derive = "1.0.94"
deflate = "0.7.20"
base64 = "0.10.1"
lazy_static = "1.3.0"

[dependencies.web-sys]
version = "0.3.25"
features = [
  'Window',
]

[dev-dependencies]
wasm-bindgen-test = "0.2"